Releasing a new version
=======================

This project adheres to the `Semantic Versioning`_ specification by Tom Preston-Werner.


Requirements
------------

Packages::

$ pip install -r requirements-dev.txt -r docs/requirements-docs.txt
$ pip install wheel twine


Process
-------

* Bump version:

  * telegram/version.py
  * docs/source/conf.py

* Log changes to:

  * CHANGES.rst

* Run tests::
  
  $ make test
  
* Build source distribution::

  $ python setup.py sdist bdist_wheel
  
* Register new version (obsolete, not needed)::

  $ python setup.py register
  
* Upload to PyPI (-s to sign the package with your GnuPG key)::
 
  $ twine upload -s dist/python*
  
* Commit the version bump and add tag::

  $ git commit -a -m 'Bump version to v<VERSION>'
  $ git push

* Create a `new release`_:

  * Tag version: v<VERSION>
  * Release title: v<VERSION>
  * Description: <logs from CHANGES.rst>
  * Upload the source distribution from pypi as binary attachment + asc (gpg signature) + sha1 (create it yourself).

* Documentation::

  * Build localy
    $ python setup.py build_sphinx
  * Fix any errors in the build
  * On  `Readthedocs dashboard`_ trigger a build for stable release.

* `Close milestones`_ for this version.

* Test in a clean virtualenv that ``pip install python-telegram-bot`` works with the new version.


Public Announcements
--------------------

Please use the following channels/groups to announce a new version release:

* `@pythontelegrambotgroup`_
* `@pythontelegrambotchannel`_

.. _`Semantic Versioning`: http://semver.org/
.. _`New release`: https://github.com/python-telegram-bot/python-telegram-bot/releases/new
.. _`Close milestones`: https://github.com/python-telegram-bot/python-telegram-bot/milestones
.. _`@pythontelegrambotgroup`: https://telegram.me/pythontelegrambotgroup
.. _`@pythontelegrambotchannel`: https://telegram.me/pythontelegrambotchannel
.. _`Readthedocs dashboard`: https://readthedocs.org/projects/python-telegram-bot/